services:
  - type: web
    name: global-viagem-assistente
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --timeout 120 --workers 1 --threads 8
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
