services:
  - type: web
    name: global-viagem-assistente
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=/opt/render/project/src gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: AMADEUS_API_KEY
        sync: false
      - key: AMADEUS_API_SECRET
        sync: false
